"""schema inicial

Revision ID: 0a9551ba0ccd
Revises: 
Create Date: 2026-05-19 13:15:07.766995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9551ba0ccd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('op_id', sa.Integer(), nullable=True),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=80), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('prazo_final', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('atendente', sa.String(length=100), nullable=False),
    sa.Column('alta_prioridade', sa.Boolean(), nullable=False),
    sa.Column('caminho_pasta', sa.String(length=500), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.Column('arquivada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    setores = sa.table(
        'setor',
        sa.column('nome', sa.String(length=100))
    )
    op.bulk_insert(setores, [
        {'nome': 'Atendimento'},
        {'nome': 'Criação'},
        {'nome': 'Projeto'},
        {'nome': 'Compras/Estoque'},
        {'nome': 'PCP'},
        {'nome': 'Arte Final'},
        {'nome': 'Pré-impressão'},
        {'nome': 'Impressão'},
        {'nome': 'Marcenaria'},
        {'nome': 'Acabamento'},
        {'nome': 'Terceirização'},
        {'nome': 'Expedição'},
        {'nome': 'Operacional'},
    ])
    op.create_table('historico_op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['ops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op_setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['ops.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('liberada', sa.Boolean(), nullable=True),
    sa.Column('entregue', sa.Boolean(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('enviada_validacao_em', sa.DateTime(), nullable=True),
    sa.Column('validada_em', sa.DateTime(), nullable=True),
    sa.Column('recusada_em', sa.DateTime(), nullable=True),
    sa.Column('entregue_em', sa.DateTime(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_recusa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['op_id'], ['ops.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    op.drop_table('users')
    op.drop_table('tarefas')
    op.drop_table('op_setor')
    op.drop_table('historico_op')
    op.drop_table('setor')
    op.drop_table('ops')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
